---
layout: resource
category: beginners
---
= If Statement Comprehension Questions

. {blank}
+
--
The outcome of each logical operator given two inputs can be organized into a *truth table*.
A truth table shows the conditions when the logical operator returns true (1) or false (0).
The following truth table for the AND operator (`&&`) is given.
Complete the table for the other operators.

[[logic-1]]
[cols="2*,m,3*e",options="header",role="truth-test"]
|===========================================
|Input A |Input B |``A && B`` |``A \|\| B`` |``A ^ B`` |``!A``

|0 |0 |0 | 0| 0| 1
|0 |1 |0 | 1| 1| 1
|1 |0 |0 | 1| 1| 0
|1 |1 |1 | 1| 0| 0
|===========================================
--

. {blank}
+
--
Complete the following truth table.

[[logic-2]]
[cols="3*,5*e",options="header",role="truth-test"]
|=======================================================================
|``A`` |``B`` |``C`` |``A && B \|\| C`` |``A && (B \|\| C)`` |``!(A && B)`` |``!(A && B) ^ C`` |``(A && (B \|\| C)) ^ !(A && B)``

|0 |0 |0 | 0| 0| 1| 1| 1

|0 |0 |1 | 1| 0| 1| 0| 1

|0 |1 |0 | 0| 0| 1| 1| 1

|0 |1 |1 | 1| 0| 1| 0| 1

|1 |0 |0 | 0| 0| 1| 1| 1

|1 |0 |1 | 1| 1| 1| 0| 0

|1 |1 |0 | 1| 1| 0| 0| 1

|1 |1 |1 | 1| 1| 0| 1| 1
|=======================================================================
--

. Determine whether the following conditions return true or false:

.. ``1==2``
.. ``6>6``
.. ``!true``
.. ``1+2==5||7<=7``
.. ``0``
.. ``!false && true``
.. ``7%4%2==7/5``
.. ``1``
.. ``(1==2^4==3)^(1<2^4<3)``
.. ``!(6!=5) || !(5>8) && 7+8 >= 6+9``

. Determine an If condition that can be used to solve the following
scenarios.

.. Sickle cell anemia is a genetic blood condition in which a person has a
shortage of healthy red blood cells. All humans acquire either a normal
hemoglobin gene or a hemoglobin S gene from each of their parents. A
person suffering from sickle cell anemia obtained a hemoglobin S gene
from both of his or her parents. Jimbob wants you to write an if
condition that will help him determine if he has sickle cell anemia.
... Let F be a boolean variable that stores if the gene inherited by his
father is the hemoglobin S gene.
... Let M be a boolean variable that stores if the gene inherited by his
mother is the hemoglobin S gene.
..  Naqvi and Wesley are playing Settlers of Catan. In order to determine
the turn order, both of them roll two dice, and the values of the two
dice are added. The player who rolls the higher sum goes first. If the
two sums are the same, whoever rolled the highest number goes first. If
both of them rolled the same values, Naqvi goes first. Write an if
condition that will help them determine who goes first in Settlers of
Catan.
...  Let N1 and N2 be the values of the two dice that Naqvi rolled
...  Let W1 and W2 be the values of the two dice Wesley rolled.
..  Valerie asks her friend Terry if she can get a ride to Pacific Mall.
Terry will only give Valerie a ride if he has room in his car. His
unusual car can only fit two other people and he already promised to
drive Chris, Hans, and Victor, assuming they need to go. Also, Terry,
hating grade 11's for some unexplained reason, will prioritize Chris,
Hans, and Victor before giving Valerie a ride. Write an if condition
that determines if Valerie will get a ride.
...  Let B be a boolean variable that stores if Chris needs a ride.
...  Let H be a boolean variable that stores if Hans needs a ride.
...  Let V be a boolean variable that stores if Victor needs a ride.

. {blank}
+
--
Write a program that compares three integers, _a_, _b,_ and _c_. Have
the program output the number that is neither the smallest nor the
largest of the three. Assume all three inputs have different values.

**Input:** _a b c_

**Output:** The median of the three inputs

.Sample Runs
[cols=",",options="header",]
|================
|Input |Output
|1 3 7 |3
|8 -9 10 |8
|-56 -58 -57 |-57
|================
--

. {blank}
+
--
Write a program that determines if a year is a leap year. Any year
divisible by 4 is a leap year. However, if the year is also divisible by
100 and not divisible by 400, the year is *not* a leap year. Output "Y"
if the input is a leap year; otherwise, output "N".

.Sample Runs
[cols=",,,,,,,",options="header",]
|==========================================
|Input |2016 |2005 |2000 |1900 |576 |1 |500
|Output |Y |N |Y |N |Y |N |N
|==========================================
--

. {blank}
+
--
Write a program that accepts three integer side lengths of a
triangle, _a, b,_ and _c_. a,b,c > 0.

* First and foremost, if the side lengths form a right angle triangle,
output "Right Angle".

* If the side lengths form an equilateral triangle, output "Equilateral".
* If the side lengths form an isosceles triangle, output "Isosceles".
* If the side lengths form a scalene triangle that is not a right angle
triangle, output "Scalene".
* If the side lengths cannot make a triangle, output "Triangle Not
Possible".

.Sample Runs
[cols=",",options="header",]
|=============================
|Input |Output
|7 7 7 |Equilateral
|6 5 6 |Isosceles
|4 5 6 |Scalene
|5 13 12 |Right Angle
|1 2 3 |Triangle Not Possible
|16 8 7 |Triangle Not Possible
|=============================
--

. Mr. Chow is back and his code looks atrocious. Sure, his code works,
but it is very hard to read and is filled with redundant comparisons.
Your job is to change *Mr. Chow's if conditions* so that it makes more
sense.

[source,role=linenos]
----
#include <iostream>
using namespace std;
// This program takes a student's marks and outputs a letter grade
// The input will ALWAYS be an integer between 0 and 100 inclusive
int main() {
    int mark;
    cin >> mark;
    if (mark >= 80) {
        cout << "You get an A!";
    }
    else if(mark >= 60 && mark < 70){
        cout << "You get a C!";
    }
    else if(mark >= 70 && mark < 80){
        cout << "You get a B!";
    }
    else if(mark >= 50 && mark < 60){
        cout << "You get a D!";
    }
    else if(mark < 50){
        cout << "You get to TRY AGAIN! :D";
    }
}
----

++++
<style>
.truth-test td em { opacity: 0 }
.truth-test td input { width: 75px; }
</style>
<script>
SCRIPTS.add(function() {
  var tests = $('.truth-test'),
      refs = {};

  tests.each(function() {
    var ems = $(this).find('td > p > em'),
        id = $(this).attr('id');

    ems.each(function(j) {
      var ref = id + '-' + j;
      refs[ref] = $(this).text();
      $(this).replaceWith("<input type='text' placeholder='...' data-ref='" + ref + "'>");
    });

    $(this).after("<div class='paragraph'><button class='button-primary' data-ref=" + id + ">Check answers</button> <span style='font-size:1em;padding:3px;margin-left:5px'></span></div>");
  });

  $('button[data-ref]').click(function() {
    var test = $('#' + $(this).data('ref')),
        inputs = test.find('input[data-ref]'),
        errors = 0;

    inputs.each(function() {
      var check = refs[$(this).data('ref')],
          val = $(this).val().trim().toLowerCase();

      if (val === 'true') val = '1';
      else if (val === 'false') val = '0';

      $(this).attr('title', '').removeClass('success error');
      if (check === val) {
        $(this).addClass('success');
      } else {
        errors++;
        $(this).addClass('error');

        if (val.length) {
          $(this).attr('title', 'Correct answer: ' + check);
        }
      }
    });

    if (errors === 0) {
      $(this).next().removeClass().addClass('label success').text('All correct!');
    } else {
      $(this).next().removeClass().addClass('label error').text('You have ' + errors + ' error' + (errors > 1 ? 's' : '') + '.');
    }
  });
})
</script>
<noscript><style>.truth-test td em {opacity: 1}</style></noscript>
++++
