---
liquid: true
layout: lesson
category: beginners
lesson: 12
---
= Other Containers

Goal: To know how and when to use {cpp} containers

== Vectors

Vectors are containers used to store an unknown number of elements.
In other languages, vectors are also known as flexible arrays.
Vectors allow elements to be added or removed at any given time.
This means that the *size of a vector can change*.
Elements in a vector have indexes and can be accessed like an array.
Vectors can be used if the *`<vector>` library* is included.
Typically, arrays are used over vectors whenever possible.
Vectors are only used when the size of an array will change frequently.
Info on vectors and their member functions can be found
http://www.cplusplus.com/reference/vector/vector/[here]:

.Example Code:
[source,role=linenos]
----
#include <iostream>  // cin, cout
#include <vector>    // vector container

using namespace std;

int main() {
    vector<int> vec; // initializes a vector of integers
    int temp;        // used for vector.push_back

    cout << "Add some numbers to the vector" << endl;
    cout << "Enter 0 to stop entering numbers" << endl;
    while (true) {
        cin >> temp;     // gets user input
        if (temp == 0) { // if 0 is inputted, the loop breaks
            break;
        }
        vec.push_back(temp); // adds an element to the end of the vector
    }

    // vec.size returns the size of the vector
    cout << "Your vector has " << vec.size() << " elements: ";
    // lists all elements in the vector
    for (int i=0; i<vec.size(); i++){
        cout << vec[i] << " ";  // elements in a vector have indexes too.
    }
    cout << endl;
    return 0;
}
----

.Sample run:
....
>>> Add some numbers to the vector
..  Enter 0 to stop entering numbers
2 3 4 5 6 0
>>> Your vector has 5 elements: 2 3 4 5 6
....

== Queues (First-in, First-out)

Queues are containers used to store an unknown number of elements. The
*first element* that is added to a queue will always be the *first
element* to be removed from a queue. *The last element* that is added to
a queue will be the *last element* to be removed. Queues do not allow
every element to be accessed, only the first and the last element in a
queue. They are often used to simulate queues and lines in real life.
Queues can be used if the *`<queue>` library* is included.

More info on queues and their member functions can be found
http://www.cplusplus.com/reference/queue/queue/[here]:

.Example Code:
[source,role=linenos]
----
#include <iostream>  // cin, cout
#include <queue>     // queue container

using namespace std;

int main() {
    queue<int> line;    // initializes queue of integers
    int temp;           // variable for user input

    cout << "How many numbers are in the queue?" << endl;
    cin >> temp;
    for (int i=0; i<temp; i++) {
        line.push(i);   // adds an element to the back of the queue
    }

    cout << "How many numbers will leave the queue?" << endl;
    cin >> temp;
    for (int i=0; i<temp; i++) {
        line.pop(); // removes an element from the front of the queue
    }

    // line.size returns the size of the queue
    cout << "The queue has " << line.size() << " elements." << endl;

    // line.front and line.back returns the first and last element
    cout << "The first element is " << line.front() << endl;
    cout << "The last element is " << line.back() << endl;
    return 0;
}
----

.Sample Run:
....
>>> How many numbers are in the queue?
8
>>> How many numbers will leave the queue?
5
>>> The queue has 3 elements.
..  The first element is 5
..  The last element is 7
....

== Stacks (Last-in, First-out)

Stacks are containers used to store an unknown number of elements. The
*first element* that is added to a stack will be the *last element* to
be removed from a stack, and the *last element* that is added to a stack
will be the *first element* to be removed. Only the top element in a
stack can be accessed. Stacks can be used if the *`<stack>` library* is
included. More info on stacks and their member functions can be found
http://www.cplusplus.com/reference/stack/stack/[here]:

.Example Code:
[source,role=linenos]
----
#include <iostream>  // cin, cout
#include <stack>     // stack container

using namespace std;

int main () {
    stack<int> myStack; // initializes a stack
    int temp;           // variable for user input

    cout << "Type in a number to add it to the stack." << endl;
    cout << "Press 0 to pop an element or -1 to exit." << endl;
    while (true) {
        cin >> temp;            // gets user input
        if (temp == -1) {
            break;              // exit user input
        } else if (temp == 0) {
            myStack.pop();      // removes the top element of a stack
        } else {
            myStack.push(temp); // adds element to the top of the stack
        }
    }

    cout << "Your stack has " << myStack.size() << " elements." << endl;
    // myStack.top returns the element on the top of the stack
    cout << "The element on the top of the stack is " << myStack.top();
    return 0;
}
----

.Sample Run:
....
>>> Type in a number to add it to the stack.
..  Press 0 to pop an element or -1 to exit.
3 4 6 0 2 3 0 0 0 8 -1
>>> Your stack has 2 elements.
..  The element on the top of the stack is 8
....

== Pair

Pairs are used to store *two data values.* They are often used in
conjunction with other containers such as arrays or vectors. A frequent
scenario that uses pairs is coordinates. In that scenario, an array of
coordinates can be made with pairs. Pairs can be used if the *`<utility>`
library* is included. More info on pairs and their member functions can
be found http://www.cplusplus.com/reference/utility/pair/[here]:

.Example Code:
[source,role=linenos,subs="verbatim,quotes"]
----
#include <iostream>  // cin, cout
#include <utility>   // stack container
#include <string>    // string container
// this program stores the titles and ratings of shows

using namespace std;

int main() {
    int numShows;    // variable that stores the number of shows
    // Makes an array of pairs. Each pair has a string and an integer
    // string is the first data value of pair, integer is the second
    pair<string, int> shows[numShows];

    cout << "How many shows are there? ";
    cin >> numShows;

    for (int i=0; i<numShows; i++) {            // for loop for user input
        cout << "What's the show's name: ";
        cin.ignore(); // **always** put this before getline()

        // goes to the ith pair of the array, and stores a string to
        // the "first" variable of that pair
        getline(cin, shows[i].first);

        cout << "What's its rating: ";
        // stores integer in the second variable of the ith pair
        cin >> shows[i].second;
    }

    int x; // variable to store the show to be looked at
    cout << "What show do you want to know about?";
    cin >> x;

    // accesses the value of the (x-1)th pair. Remember that arrays are
    // indexed starting with 0
    cout << shows[x-1].first << " has a rating of " << shows[x-1].second << endl;
    return 0;
}
----

.Sample Run:
....
How many shows are there? 3
What's the show's name: Bobby the Construction Worker
What's its rating: 3
What's the show's name: Doris the Expeditioner
What's its rating: 9
What's the show's name: The Magic Garbage Truck
What's its rating: 6
What show do you want to know about? 2
Doris the Expeditioner has a rating of 9
....

== Maps

Maps are containers that *store corresponding data values*. Instead of
using an index to refer to a specific data value, it uses another data
value. Maps are used whenever a value corresponds to another value. For
example, Roman Numerals would use maps because it has a
character-integer correspondence (V with 5). That being said, *a data
value cannot correspond to two or more other data values*. Also, if a
map receives an index that doesn't have a corresponding data value, it
*returns 0* if the corresponding data value should be a an integer or an
*empty string* *("")* if the data value should be a string. Maps can be
used in a code file if the *<map> library* is included. More info on
maps and their member functions can be found
http://www.cplusplus.com/reference/map/map/[here].

.Example Code:
[source,role=linenos]
----
#include <iostream>  // cin, cout
#include <map>       // map container
#include <string>    // string container

using namespace std;

// map pairs each Canadian province with its two letter abbreviation
int main() {
    // initializes a map where a string corresponds to another string
    map<string, string> provinces;
    provinces["AB"] = "Alberta";          // gives value for each element
    provinces["BC"] = "British Columbia"; // notice how this map has no size
    provinces["MB"] = "Manitoba";         // this list could be gigantic
    provinces["NB"] = "New Brunswick";    // the list could just continue
    provinces["PE"] = "PEI";              // assuming we have much more provinces
    // ...This goes on for the remaining 8 provinces/territories

    string abbreviation; // string for user input

    cout << "Hey! Which province/territory do you live in? ";
    cin >> abbreviation;

    // province[s] would return the string that corresponds with string s
    cout << "WOW! You live in " << provinces[abbreviation] << "?!?!" << endl;
    return 0;
}
----

.Sample Run 1:
....
Hey! Which province/territory do you live in? MB
WOW! You live in Manitoba?!?!
....

.Sample Run 2:
....
Hey! Which province/territory do you live in? XX
WOW! You live in ?!?!
....

== In Summary

* A vector is a container that acts like an array, but can change size
* A queue is a container with a first-in, first-out (FIFO) policy when
adding and removing elements
* A stack is a container with a last-in, first out (LIFO) policy when
adding and removing elements
* A pair is a container that stores two data values
* A map is a container that gives a one to one correspondence between two
data values.

== Practice Questions

* http://wcipeg.com/problem/ccc14s3[The Geneva Confection]
