---
liquid: true
layout: resource
category: beginners
---
= Functions Questions

== Part I

. Write a function, _drawBox_, that draws a box out of X’s with a
given width and height. This function will have no return value.
+
For example, a 3 by 4 box will look like the following:
+
....
XXXX
X  X
XXXX
....

. Write a function that returns if a year is a leap year. This
function will return a boolean value: true or false.

    * Any year divisible by 4 is a leap year. However, if the year is
divisible by 100 and *not* divisible by 400, the year is *not* a leap
year.

. Below is the formula used to convert a temperature from Celcius to
Farenheit.
+
+\[F = (9*C)/5 + 32\]+
+
Write a function that converts a temperature from Celcius to Farenheit.
Round the final temperature to the nearest integer.

. Write a function that finds the area of a circle with a given
radius. The function will return a double with a precision of 2 decimal
places.

. {blank}
[loweralpha]
. Write a function that accepts three side lengths. It will return
whether the three sides can form a triangle.
. Modify the function so that it returns whether the three side
lengths form a right-angle triangle.

. Write a function that accepts a positive integer and returns if the
value is prime.

. {blank}
[loweralpha]
.. Write a function that accepts two strings, str1 and str2, as
arguments. Your function will search for the first occurrence of str2
within str1 and return where it is found. If str2 is not found anywhere
in str1, your function should return -1. You are basically coding the
http://www.cplusplus.com/reference/string/string/find/[find()]
function in the string library; *do not use that function*.
.. Modify your function so that the search is case insensitive.
.. Create your own
http://www.cplusplus.com/reference/string/string/replace/[replace()]
function. This function takes two strings str1, str2 and str3. Anytime
str2 is found in str1, it is replaced with str3. Return the final
string. The search is *case sensitive*.
+
.Sample Testcase:
[cols="4*m",options="header"]
|=============================================
|str1 |str2 |str3 |Return Value
|"Aayyy%lmao" |"a" |"Woah" |"AWoahyyy%lmWoaho"
|=============================================

== Part II

. Write a function that passes two integer values,a and b, by
reference. Have the function swap the values *if* the two variables if a
> b.

. {blank}
[loweralpha]
.. Write a function that takes a string as an argument and returns a
string that is in all caps.
.. Modify your function so that the string argument is changed
directly. Change the return type of the function from string to void.

. Write a function that sorts an integer array from least to greatest.
Do not use sort(). Choose one of the following sorts:

    ** https://en.wikipedia.org/wiki/Bubble_sort[Bubble Sort]
    ** https://en.wikipedia.org/wiki/Selection_sort[Selection Sort]
    ** https://en.wikipedia.org/wiki/Insertion_sort[Insertion Sort]

. Read the following piece of code and determine the following:

    ** The output
    ** The return values and parameters of each function call. *Only use an IDE to check your answer.*
+
**Code A**
++++
{% highlight cpp linenos %}
#include <iostream>
using namespace std;

int china(int a,int b){
    cout << a+b << endl;
    return a-b;
}

int germany(int a){
    return a*2-1;
}

int canada(int x, int y, int z){
    int a=germany(z)+germany(y);
    return a+x;
}

int france(int y, int x){
    int a=x-y;
    return canada(x,y,a);
}

int main(){
    int x=1,y=3,z=5;
    cout << x << " " << y << " " << z << endl;
    china(x,y);
    cout << china(z,y) << endl;
    cout << canada(x,y,z) << endl;
    cout << germany(france(x,z)) << endl;
    return 0;
}
{% endhighlight %}
++++
+
**Code B**
++++
{% highlight cpp linenos %}
#include <iostream>

using namespace std;

int kazakhstan(int b,int a){
    return a-b;
}

int kyrgyzstan(int a,int b){
    int c=a*b;
    cout << c << " ";
    return c+b+a;
}

int azerbaijan(int& a,int& b){
    int c=kazakhstan(b,a);
    a=c*a;
    b=c*b;
    return c;
}

int main(){
    int a=5,b=10;
    cout << a << " " << b << endl;
    cout << kazakhstan(a,b) << endl;
    cout << kyrgyzstan(kazakhstan(a,b),a+b) << endl;
    cout << azerbaijan(b,a) << endl;
    cout << a << " " << b;
    return 0;
}
{% endhighlight %}
++++
+
**Code C**
++++
{% highlight cpp linenos %}
#include <iostream>
using namespace std;

int brazil(int& a){
    a=a*2-1;
    return a-1;
}

int chile(int& y,int& x){
    y+=3;
    x+=2;
    return y+x;
}

int peru(int& x,int& y){
    x--;
    chile(x,y);
    return x*(x-y);
}

int main(){
    int x=2,y=5;
    brazil(y);
    cout << brazil(x)+y << endl;
    cout << chile(x,y) << endl;
    cout << x << " " << y << endl;
    x=peru(y,x);
    cout << x << " " << y << endl;
    return 0;
}
{% endhighlight %}
++++

== Part III

. Write a recursive function that takes an integer _n_ and returns _n_
factorial.

. Write a recursive function that takes an integer _n_ and returns the
__n__th
https://www.mathsisfun.com/algebra/triangular-numbers.html[triangular
number]. *Do not use a loop or ++\(\dfrac{n (n + 1)}{2}\)++.*

. Write a recursive function that takes a string argument and reverses
the string.

. Write a recursive function that finds the nth term of the
https://www.mathsisfun.com/numbers/fibonacci-sequence.html[Fibonacci
Sequence]. This is also known as "`the worst Fibonacci function`" but do
it anyways.

. Write a recursive function that finds the GCF of two integers using
the
https://www.khanacademy.org/computing/computer-science/cryptography/modarithmetic/a/the-euclidean-algorithm[Euclidian
method].

. Write a recursive function that returns a value from
http://www.mathsisfun.com/pascals-triangle.html[Pascal`'s Triangle]
given its row and column. The row and column numbers in Pascal’s
Triangle start at 0.

*Challenge:* Solve the http://wcipeg.com/problem/ccc05j5[J5 problem] for
the 2015 CCC. This problem will use recursion.

== PART IV

. {blank}
[loweralpha]
.. A formula for the area of a triangle
is +\(A = \frac{b*h}{2}\)+ . Have a function named `areaT` return
the area of a triangle given its base and height. The parameters and
return type will be integers.
.. One can also use Heron`'s Formula to find the area of a triangle with
side lengths a, b, and c.
+
+\[A = \sqrt{s(s - a)(s - b)(s - c)}\]+
+
The value of s is the semiperimeter of the triangle:
+\(\dfrac{a + b + c}{2}\)+
+
Create another function named `areaT` that takes three integer side
lengths and returns the area using Heron`'s Formula.
.. Create another function named `areaT` that takes the side length of an
equilateral triangle and returns the area of that triangle.

== Sample Calls

[cols="2*m",options="header",]
|==========================
|Call |Output
|drawBox(4,5); |
|drawBox(10,1); |XXXXXXXXXX
|drawBox(5,0); |
|==========================

Sample Call

[cols="2*m",options="header",]
|========================
|Call |Return Value
|isLeapYear(1992); |true
|isLeapYear(1900); |false
|isLeapYear(2000); |true
|========================
